version: '2'
services:
    zoo1:
        image: zookeeper
        restart: always
        container_name: zoo1
        ports:
            - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        networks:
            zk-test:
                ipv4_address: 10.10.10.11
    zoo2:
        image: zookeeper
        restart: always
        container_name: zoo2
        ports:
            - "2182:2181"
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        networks:
            zk-test:
                ipv4_address: 10.10.10.12

    zoo3:
        image: zookeeper
        restart: always
        container_name: zoo3
        ports:
            - "2183:2181"
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        networks:
            zk-test:
                ipv4_address: 10.10.10.13
    worker1:
        build:
            ./py_work
        image: zk_work:1 
        container_name: worker1
        hostname: worker1
        environment:
            MY_IP: 10.10.10.21
        volumes:
        - /tmp/zk_work:/tmp/zk_work
        networks:
            zk-test:
                ipv4_address: 10.10.10.21    
    worker2:
        build:
            ./py_work
        image: zk_work:1
        container_name: worker2
        hostname: worker2
        environment:
            MY_IP: 10.10.10.22
        volumes:
        - /tmp/zk_work:/tmp/zk_work
        networks:
            zk-test:
                ipv4_address: 10.10.10.22
    worker3:
        build:
            ./py_work
        image: zk_work:1
        container_name: worker3
        hostname: worker3
        environment:
            MY_IP: 10.10.10.23
        volumes:
        - /tmp/zk_work:/tmp/zk_work
        networks:
            zk-test:
                ipv4_address: 10.10.10.23

networks:
    zk-test:
        external: true
